# books section
01-1:
    type: book
    title: "Introduction to Algorithms"
    author:
        - Cormen, Thomas H.
        - Leiserson, Charles E.
        - Rivest, Ronald L.
        - Stein, Clifford
    date: 2009

01-2:
    type: book
    title: "Introduction to the Theory of Computation"
    author: Sipser, Michael
    date: 2012

01-3:
    type: book
    title: "Computer Networking: A Top-Down Approach"
    author:
        - Kurose, James F.
        - Ross, Keith W.
    date: 2017

01-4:
    type: book
    title: "Operating Systems: Three Easy Pieces"
    author:
        - Arpaci-Dusseau, Remzi H.
        - Arpaci-Dusseau, Andrea C.
    date: 2018

01-5:
    type: book
    title: "Modern Operating Systems"
    author: Tanenbaum, Andrew S.
    date: 2014

01-6:
    type: book
    title: "The C++ Programming Language"
    author: Stroustrup, Bjarne
    date: 2013

01-7:
    type: book
    title: "Effective Modern C++"
    author: Meyers, Scott
    date: 2014

01-8:
    type: book
    title: "Programming in Scala"
    author:
        - Odersky, Martin
        - Spoon, Lex
        - Venners, Bill
    date: 2016

01-9:
    type: book
    title: "Thinking Functionally with Haskell"
    author: Bird, Richard
    date: 2015

01-10:
    type: book
    title: "Concepts of Programming Languages"
    author: Sebesta, Robert W.
    date: 2016
